//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yodii.Engine.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yodii.Engine.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Yodii.Lab&gt;
        ///  &lt;Services&gt;
        ///    &lt;Service FullName=&quot;IService1&quot;&gt;
        ///      &lt;Generalization /&gt;
        ///      &lt;X&gt;-637.593810037161&lt;/X&gt;
        ///      &lt;Y&gt;-344.269395424875&lt;/Y&gt;
        ///    &lt;/Service&gt;
        ///    &lt;Service FullName=&quot;IService1-1&quot;&gt;
        ///      &lt;Generalization&gt;IService1&lt;/Generalization&gt;
        ///      &lt;X&gt;-791.670431176708&lt;/X&gt;
        ///      &lt;Y&gt;-246.944802537054&lt;/Y&gt;
        ///    &lt;/Service&gt;
        ///    &lt;Service FullName=&quot;IService1-2&quot;&gt;
        ///      &lt;Generalization&gt;IService1-1&lt;/Generalization&gt;
        ///      &lt;X&gt;-976.34265228201&lt;/X [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseGraph4 {
            get {
                return ResourceManager.GetString("BaseGraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Yodii.Lab&gt;
        ///  &lt;Services&gt;
        ///    &lt;Service FullName=&quot;Service1&quot;&gt;
        ///      &lt;Generalization /&gt;
        ///    &lt;/Service&gt;
        ///    &lt;Service FullName=&quot;Service2&quot;&gt;
        ///      &lt;Generalization /&gt;
        ///    &lt;/Service&gt;
        ///    &lt;Service FullName=&quot;Service3&quot;&gt;
        ///      &lt;Generalization /&gt;
        ///    &lt;/Service&gt;
        ///    &lt;Service FullName=&quot;Service3.1&quot;&gt;
        ///      &lt;Generalization&gt;Service3&lt;/Generalization&gt;
        ///    &lt;/Service&gt;
        ///    &lt;Service FullName=&quot;Service3.2&quot;&gt;
        ///      &lt;Generalization&gt;Service3&lt;/Generalization&gt;
        ///    &lt;/Ser [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Graph005 {
            get {
                return ResourceManager.GetString("Graph005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Yodii.Lab&gt;
        ///  &lt;Services&gt;
        ///    &lt;Service FullName=&quot;ServiceA&quot;&gt;
        ///      &lt;Generalization /&gt;
        ///    &lt;/Service&gt;
        ///    &lt;Service FullName=&quot;ServiceAx&quot;&gt;
        ///      &lt;Generalization&gt;ServiceA&lt;/Generalization&gt;
        ///    &lt;/Service&gt;
        ///    &lt;Service FullName=&quot;ServiceB&quot;&gt;
        ///      &lt;Generalization /&gt;
        ///    &lt;/Service&gt;
        ///  &lt;/Services&gt;
        ///  &lt;Plugins&gt;
        ///    &lt;Plugin&gt;
        ///      &lt;FullName&gt;PluginA-1&lt;/FullName&gt;
        ///      &lt;Service&gt;ServiceA&lt;/Service&gt;
        ///      &lt;ServiceReferences /&gt;
        ///    &lt;/Plugin&gt;
        ///    &lt;Plugin&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Valid001a {
            get {
                return ResourceManager.GetString("Valid001a", resourceCulture);
            }
        }
    }
}
